name: Master

on:
  push:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          java-package: jdk
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew buildJar --no-daemon

      - name: Upload Plugin Jar
        uses: actions/upload-artifact@v3
        with:
          name: ChunkyAnimatePlugin
          path: build/libs/ChunkyAnimate.jar
      - name: Upload Standalone Jar
        uses: actions/upload-artifact@v3
        with:
          name: ChunkyAnimateStandalone
          path: build/libs/ChunkyAnimate-Standalone.jar
